# fly.toml app configuration file generated for zero2prod on 2025-04-27T14:18:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zero2prod'
primary_region = 'fra'

[build]

[env]
APP_DATABASE__DATABASE_NAME = 'zero2prod'
APP_DATABASE__HOST = 'zero2prod-db.flycast'
APP_DATABASE__PORT = '5432'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
