# fly.toml app configuration file generated for zero2prod-ancient-star-5964 on 2025-04-27T12:11:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zero2prod-ancient-star-5964'
primary_region = 'fra'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
