application:
  host: 0.0.0.0
  base_url: "http://127.0.0.1" # Set in fly with secrets!
database:
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "newsletter@tchau.store"
